version: 2

models:
  - name: users
    columns:
      - name: username
        tests:
          - unique
          - not_null
      - name: groupname
        tests:
          - not_null

  - name: parent_and_child_loads
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: cons_id
        tests:
          - not_null
  
  - name: parent_loads
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: cons_id
        tests:
          - not_null

  - name: ref_event
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: descr
        tests:
          - not_null
          - unique 
